### PR TITLE
Implements python3 support

### LINKED ISSUE #18: ubi reader and scripts are broken when intstalled in a python3 environment
When installing ubi_reader in a python3 environment (E.g. Ubuntu 16.04 or newer), the scripts are broken.

ubi_reader is usually installed with
```
sudo pip install ubi_reader
```

This installs ubi_reader with a python3 shebang, resulting in the interpreter complaining about the python2 syntax:
```
$ ubireader_extract_images --help
  File "/usr/local/bin/ubireader_extract_images", line 38
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

### PR DESCRIPTION
**Pull request by smipi1**
Should resolve #18

### CODE REVIEW

**Comment by smipi1** [comment]
Hi @jrspruitt,

Better late than never I guess. I got around to the python3 conversion this weekend, but I have not been able to test it extensively.

As already agreed, I opted not to support both python2 and 3; the internals get too messy.

In the changes, I had to decide what to internally represent as bytes (the default), and what to internally represent as a string. I opted to internally keep as much bytes as possible, and only to convert the volume names to strings.

Regards
@smipit

**Comment by jrspruitt** [comment]
Hi @smipi1,

Thank you very much, I haven't had a chance to test it yet but I created a new branch Python3 to get things going. Since ubi_reader is included in some other applications and packages, I believe this is probably the best approach for now, so it doesn't break other people's stuff. Then once Python2 is officially EOL'd maybe this will get moved to master.

-Jason

**Comment by smipi1** [comment]
@jrspruitt,

Hold on a little. It looks like supporting both python2.7.x and python3 is fairly simple.

If this works, would you be amenable to merging the codebase?

Regards,
@smipi1

**Comment by smipi1** [comment]
You would be surprised how little is required for compatibility with both. ;-)

**Pull request merged**
