### PR TITLE
Unify the CLI

### PR DESCRIPTION
**Pull request by AT0myks**
Hi, right now if someone wants to use the scripts inside of Python, for example `ubireader_extract_files`, they would have to do something like `subprocess.run(["ubireader_extract_files", "/path/to/file"])` which is frustrating knowing that ubireader itself is written in Python.

This PR integrates the scripts into ubireader as functions so that they can be used directly by other Python code.

Here's the summary of the changes:

- Move the `scripts` folder under `ubireader` and remove the `ubireader_` prefix
- For each script, starting from after the line `args = parser.parse_args()`, move the code to a function named after the script
- Replace all `parser.error` calls in that code by `raise UBIReaderError` (a new exception)
- Merge the common arguments into `parser_base` and use it as a parent parser for all subcommands
- Move each script's remaining arguments to their related subparser
- Link each subparser to its target function (`parser.set_defaults`)

Now the example becomes

```py
from ubireader.scripts.extract_files import extract_files
extract_files("/path/to/file")
```

Even if most of the scripts are meant to display information to the user, and using them internally will print information that you might not want to see output from your own script, at least the possibility is there.

Some optimizations could have been made but I didn't want to make too many modifications for now to keep reviewing the changes pretty straightforward.

There are some very small differences inherent to moving from "argparse code" to "function code" (if that makes any sense), but it should be functionally identical to the scripts-based version. The only difference is that for example instead of `ubireader_extract_files` it's now `ubireader extract-files`.

Some notes:

- The 4 subcommands that have the `--leb-size` argument have the same `dest='block_size'` as the common argument `--peb-size` which means only the last one to be specified will take effect (from what I've seen it's fine and using any of the two will give the same result)
- Although ubireader is clearly aimed at being used on Linux, a fair amount of it works on Windows

### CODE REVIEW

**Comment by jrspruitt** [comment]
Hi AT0myks,

I appreciate the effort, but this fundamentally breaks how ubi_reader is being used in every way I've been made aware of. The scripts are meant to be installed in the system, and are expected to be there by other projects.  For the most part they are just trying to get user input, the actual extraction doesn't require much code, if you'd like to include the functionality in your own Python scripts.

The spelling corrections and unused imports are much appreciated, but in the future, it'd be preferred if you submitted one PR per issue, as I can't accept the scripts change, but I could have the imports and then spelling.

I'm not sure how the custom Exception is being used, I see it's added, but not the errors that are throwing it.  

-Jason

**Comment by AT0myks** [comment]
I thought about that and I understand.
What about instead of replacing the scripts by a CLI we added the CLI as another option of interfacing with ubireader, or would that be too confusing?
Even if it's not fully supported, this would help for Windows where the scripts don't work out of the box (as far as I know).
I think we could at least salvage some parts of this PR like the parent parser that avoids repeating the same options for each script.

I didn't want to multiply the number of PRs as I thought the changes were small enough, but that's noted for potential future ones.

For the exception, as I said it was used to replace the calls to `parser.error` that appear in each script.

Also while I'm here, now that Python 2 is considered unsupported, which 3.x version do you plan on making the minimum?
I would say not older than 3.7 as it's the oldest release that is still maintained.

**Comment by jrspruitt** [comment]
Okay I found where the exceptions were raised, sorry missed that on the first look through.

As for the PRs, it's a lot easier to do one per subject, even when they are small, I have a hard time with this myself, but it keeps things cleaner and easier to manage when merging.

For Python3 the oldest that can be supported would be nice, but obviously for the same reason of dropping 2, it can only go so far.

I am unfamiliar with Python on Windows, it's never been a priority because in the past python-lzo, which is required, was not available, or not easily installed. I am not sure if that has changed or not. The Linux functionality can't change, just due to expectations from other projects that use ubi_reader, but if there is an add on way, I'm all for that.

Consolidating some script code could be a good idea, it would make adding new flags easier. I'm pretty sure they are the same across most of the scripts.

-Jason

**Comment by AT0myks** [comment]
I know a bit about installing python-lzo on Windows and how it's not user-friendly, but hopefully [that should change soon](https://github.com/jd-boyd/python-lzo/pull/65).

I'll start the work on adding a more platform generic CLI soon (most if not all is already done in this PR).

There are currently 10 arguments that are repeated in each script, so there's indeed some space for consolidation (this is what I described in my original post as merging the common arguments, and therefore is also already done).

**Comment by jrspruitt** [comment]
Good to hear about python-lzo. As for the platform generic CLI, as long as on Linux, it stays the same, it shouldn't be a problem. Binwalk and I believe another forensics type app expect the scripts to be how they are now. Other than that, it's included in a couple Linux package managers, so that shouldn't be an issue.

**Comment by jrspruitt** [comment]
I was just playing around with this on Win10, the only issue I had running the scripts from cmd.exe, was that the scripts need a .py extension. They were installed in PATH, and the shebang line was changed, but they are not registered with Python, if they don't have the extension. Also forgot there are a couple file types that can not be created in Windows, symlink, devices, perhaps more. So when extracting a Linux system, good chance files will be missing.

**Comment by AT0myks** [comment]
Adding the .py extension should be enough. The shebang does not need to be changed because it's part of the ones that are supported both on Unix and Windows (see [here](https://docs.python.org/3/using/windows.html#shebang-lines)).

I think the lack of complete support for Windows is acceptable (and as you say it's probably impossible to reach anyway) as long as we state in the readme that there are limitations that come with using it on this OS.

The plus is that this would add a bit of Windows compatibility and turn the internal functionality of the scripts into functions by simply rearranging some of the code, while keeping the scripts intact for Linux.

**Comment by AT0myks** [comment]
That's good timing, I was just about to open a new PR.

Maybe I should have been more clear, after our discussion I was going to leave the scripts alone (well, almost), and also I didn't intend on adding the .py extension, that was just some info I wanted to add after your previous message, sorry.

So right now this new PR is almost ready, it's basically the same as this one but keeps the scripts the same from the outside, meaning almost all of their code is moved inside ubireader but they still work exactly the same.

Should I go with that or with new suggestion where the scripts are not changed at all (meaning there is some duplicated code)?

**Comment by AT0myks** [comment]
Alright, I'm gonna make the other changes you mentioned and open a new PR. Thank you for your quick answers.

**Pull request closed without merging**
